# Generated by Django 5.1.1 on 2024-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouedkniss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
